// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHtlr1psN-M8-F5cdQDJyU4Lvt-LJVn8Q',
    appId: '1:87844356700:web:757430ae66b0de3b651c99',
    messagingSenderId: '87844356700',
    projectId: 'tixnow-e2c33',
    authDomain: 'tixnow-e2c33.firebaseapp.com',
    storageBucket: 'tixnow-e2c33.firebasestorage.app',
    measurementId: 'G-SWB6D32R8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLcl-dvCcynwfuKzmgO5nQxRD6zXQu6g4',
    appId: '1:87844356700:android:fa92666659161ad8651c99',
    messagingSenderId: '87844356700',
    projectId: 'tixnow-e2c33',
    storageBucket: 'tixnow-e2c33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKsYZTCZucVJHgmG-J-ZRoHq5V79wVJk',
    appId: '1:87844356700:ios:46acbb9ce2979b31651c99',
    messagingSenderId: '87844356700',
    projectId: 'tixnow-e2c33',
    storageBucket: 'tixnow-e2c33.firebasestorage.app',
    iosBundleId: 'com.example.tixNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSKsYZTCZucVJHgmG-J-ZRoHq5V79wVJk',
    appId: '1:87844356700:ios:46acbb9ce2979b31651c99',
    messagingSenderId: '87844356700',
    projectId: 'tixnow-e2c33',
    storageBucket: 'tixnow-e2c33.firebasestorage.app',
    iosBundleId: 'com.example.tixNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHtlr1psN-M8-F5cdQDJyU4Lvt-LJVn8Q',
    appId: '1:87844356700:web:6ada9c85b3c35f01651c99',
    messagingSenderId: '87844356700',
    projectId: 'tixnow-e2c33',
    authDomain: 'tixnow-e2c33.firebaseapp.com',
    storageBucket: 'tixnow-e2c33.firebasestorage.app',
    measurementId: 'G-P6R0KGF4GR',
  );
}
